### ISSUE TITLE
ndoe

### ISSUE THREAD

**Issue by lemonxiesf** [hai-27/vue-store#17]

**Comment by lemonxiesf** [comment]
有node代码嘛

**Comment by hai-27** [comment]
@lemonxiesf 服务端在这里[https://github.com/hai-27/store-server](https://github.com/hai-27/store-server)

**Comment by lemonxiesf** [comment]
感谢大佬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hai-27/vue-store"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 晚上10:51
收件人:&nbsp;"hai-27/vue-store"<vue-store@noreply.github.com&gt;;
抄送:&nbsp;"有些感受，只有经历过，才知"<1192001561@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hai-27/vue-store] ndoe (#17)





 
@lemonxiesf 服务端在这里https://github.com/hai-27/store-server
