### ISSUE TITLE
给个联系方式可否

### ISSUE THREAD

**Issue by biyesheji-huang** [hai-27/vue-store#3]
能否给个联系方式呢，想用你这个项目做毕业设计

**Comment by cheneycode** [comment]
QQ  393501065




| |
陈鑫
|
|
邮箱：13759893229@163.com
|

签名由 网易邮箱大师 定制

在2020年04月09日 10:13，biyesheji-huang 写道：

能否给个联系方式呢，想用你这个项目做毕业设计

**Comment by hai-27** [comment]
加你QQ了
