### ISSUE TITLE
@hi from xiaomi

### ISSUE THREAD

**Issue by macaienlei** [hai-27/vue-store#4]
hi 小龙，你目前大几了？

**Comment by hai-27** [comment]
小龙？
我现在大三。

**Comment by macaienlei** [comment]
https://www.toutiao.com/i6827788546682651140/?tt_from=weixin&utm_campaign=client_share&wxshare_count=1&timestamp=1589794793&app=news_article&utm_source=weixin&utm_medium=toutiao_android&req_id=20200518173952010014047037034A6156&group_id=6827788546682651140

**Comment by macaienlei** [comment]
@hai-27 小海，我是小米商城的工程师，你模仿商城的项目我们部门负责 😄。我们研发的同事推荐过来看到的

**Comment by macaienlei** [comment]
@hai-27 小海，我是小米商城研发，我们研发的同事推荐一篇文章介绍了你做小米商城的项目。我商城同事都对你做的项目印象深刻很赞👍。继续加油哦！ 后续欢迎你考虑来小米实习或工作哦～ 😄

**Comment by hai-27** [comment]
非常感谢！
